### ISSUE TITLE
yaml load deprecation bfModel notebook

### ISSUE THREAD

**Issue by RichardScottOZ** [Geodels/gospl#272]
**Describe the bug**
yaml error in bfModel notebook

**To Reproduce**
run bfModel notebook

**Expected behavior**
it works

**Desktop (please complete the following information):**
 - WSL

**Additional context**
```python
Traceback (most recent call last):
  File "/mnt/c/users/rscott/OneDrive - BHP/exploration2024/gospl/notebooks/bfModel/runBF.py", line 23, in <module>
    merger.mergeBackModels(backin, backout)
  File "/mnt/c/users/rscott/OneDrive - BHP/exploration2024/gospl/notebooks/bfModel/scripts/mergeBack.py", line 237, in mergeBackModels
    tStart, tEnd, tOut, outputDir, nbCPUs = readOutputs(inputs[k])
  File "/mnt/c/users/rscott/OneDrive - BHP/exploration2024/gospl/notebooks/bfModel/scripts/mergeBack.py", line 43, in readOutputs
    input = yaml.load(finput, Loader=yaml.Loader)
  File "/home/richard/miniconda3/envs/gospl-package/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1085, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "/home/richard/miniconda3/envs/gospl-package/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1037, in error_deprecation
    raise AttributeError(s)
AttributeError: 
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/mnt/c/users/rscott/OneDrive - BHP/exploration2024/gospl/notebooks/bfModel/scripts/mergeBack.py", line 43

        input = yaml.load(finput, Loader=yaml.Loader)```

**Comment by RichardScottOZ** [comment]
so a few errors in this one caused by environment installed now as opposed to time of this notebook

**Comment by RichardScottOZ** [comment]
others so far are pydata apis - not any of yours

**Comment by tristan-salles** [comment]
Yes there will be some adjustments needed to ensure that all libraries are available for `tests`. I will also update the examples according to the new capabilities of the code.
